#!/bin/bash

clear

#tableau
a=(3 5 8 10 6)
b=(6 5 4 12)
c=(14 7 5 7)

#incorpore les élément commun a dans un nouveau tableau x et b dans un nouveau tableau y.
#comparaison des tebleau x et y et incorporation des élément commun x et y (a et b) dans un nouveau tableau z qui servira de comparaison pour c.

for x in "${a[@]}"; do
	#pas de commande util ici, laisser le corp de la commande vide
	for y in "${b[@]}"; do
		if [ $x = $y ]; then
			z[${#z[@]}]=$x
		fi
	done
done

#même principe que plus haut avec le tableau c dans le nouveau tableau i et z qui vas dans K pour la comparaison.
#ensuite création de j qui contient les element commun de i et k (donc de tout les tableau).

for i in "${c[@]}"; do
	#pas de commande util ici, laisser le corp de la commande vide
	for k in "${z[@]}"; do
		if [ $i = $k ]; then
			j[${#j[@]}]=$i
		fi
	done
done

#affichage du tableau j qui contien l'élément commun des tableau a, b, c.

echo ${j[@]}




