#!/bin/bash

clear

#variables
BUFFETT="Life is like a snowball. The important thing is finding wet snow and a really long hill."
ISAY=$BUFFETT
change1=${ISAY[@]/snow/foot}
change2=${change1[@]// snow/}
change3=${change2[@]/finding/getting}
Loc=`expr index "$change3" 'w'`
ISAY=${change3::$Loc+2}

# Execute code
echo "Warren Buffett said:"
echo $BUFFETT
echo "and i say:"
echo "$ISAY"
