#!/bin/bash
clear

#créer la fonction ENGLISH_CALC
function ENGLISH_CALC {
	#implémenté les parametre 1, 2 et 3 de la fonction
	a=$1
	b=$3
	signn=$2

	#implémentation de la condition
	if [ $signn == "plus" ]; then
		#commande du parametre 2 dans le calcule
		echo "$a + $b = $(($a+$b))"
	elif [ $signn == "minus" ]; then
		#commande du parametre 2 dans le calcule
		echo "$a - $b = $(($a-$b))"
	elif [ $signn == "times" ]; then
		#commande du parametre 2 dans le calcule
		echo "$a * $b = $(($a*$b))"
	fi	
}

#test du code
ENGLISH_CALC 3 plus 5
ENGLISH_CALC 5 minus 1
ENGLISH_CALC 4 times 6
